# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cotisant',
            field=models.BooleanField(default=False),
        ),
    ]
