# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_user_cotisant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nbSessions',
            field=models.IntegerField(default=0),
        ),
    ]
