language: python
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y slapd ldap-utils
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
python:
  - 3.6
env:
  global:
    - LDAP_URL="ldap://127.0.0.1:3890"
before_script:
  - ./tests/setup_ldap.sh
script:
  - coverage run --source="coreapp" runtests.py
after_success:
  - coveralls
